version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/LaundryApp/.env

  mobile:
    build: ./mobile
    ports:
      - "8081:8081"
      - "3000:3000"

  admin:
    build: ./admin
    ports:
      - "4000:80"
